# Enable GIT dynamic version
nisse.source.jgit.dynamicVersion=true
# Fallback values for source archives (expanded by git archive via export-subst)
nisse.jgit.dynamicVersion=$Format:%(describe:tags=true)$
nisse.jgit.date=$Format:%cI$
